bundle/manifests/backstage-default-config_v1_configmap.yaml
bundle/manifests/backstage-operator.clusterserviceversion.yaml
config/manager/default-config/deployment.yaml
config/manager/default-config/route.yaml
config/manager/default-config/service.yaml
config/manager/kustomization.yaml
config/rbac/role.yaml
controllers/backstage_controller.go
controllers/backstage_controller_test.go
controllers/backstage_deployment.go
controllers/backstage_route.go
controllers/local_db_statefulset.go
examples/postgres-secret.yaml
main.go

Changes made:
Autodetect if the current cluster is OpenShift and creates a route when Backstage CR is reconciled.
Changed backstage deployment and service name to "backstage-"+ to allow the users to deploy multiple backstage CRs in the same namespace.
Changed the default value of own-runtien to true.
Note https://github.com/janus-idp/operator/issues/1: supporting host and tls in the route via Backstage CR is not in the scope of this PR. Such work shall be done later as a separate PR after the data model has been finalized.
Note https://github.com/janus-idp/operator/pull/2: unit test with isOpenShift=true is not included as OpenShift specific objects (routes, projects etc) are not currently supported by the envTest tool (see https://github.com/operator-framework/operator-sdk/issues/4434). …

Implement routing configuration for Backstage server endpoint

---

Makefile
docker/bundle.Dockerfile
docker/license_header.txt

As reported in #84, `bundle.Dockerfile` gets recreated at the root directory whenever `make bundle` is run. This PR just moves the new file to the `docker` directory. Otherwise, it can create confusion if we have both `bundle.Dockerfile` files. Worse, `make bundle-build` might not use the right `bundle.Dockerfile` after a regeneration (since it uses `docker/bundle.Dockerfile` - https://github.com/janus-idp/operator/blob/main/Makefile#L258).
- Fixes #84 
- Related to #75 
`make bundle` should not create a ` bundle.Dockerfile` file at the root directory. It should exist under `docker/` instead.

Move `bundle.Dockerfile` under `docker` directory whenever it gets regenerated

---

api/v1alpha1/backstage_types.go
bundle/manifests/backstage-default-config_v1_configmap.yaml
bundle/manifests/backstage-operator.clusterserviceversion.yaml
bundle/metadata/annotations.yaml
config/manager/default-config/db-statefulset.yaml
config/manager/default-config/deployment.yaml
config/manager/manager.yaml
controllers/backstage_controller.go
controllers/backstage_controller_test.go
controllers/backstage_deployment.go
controllers/local_db_statefulset.go
main.go

Use environment variables POSTGRESQL_IMAGE and BACKSTAGE_IMAGE to the operator container to indicate the default images used by the operator to deploy psql db and backstage application, respectively. 
Note that: 
a) If the psql db statefulset has image unset, or set to the special string {POSTGRESQL_IMAGE}, the operator will replace it with the value of the environment variable POSTGRESQL_IMAGE. Similarly BACKSTAGE_IMAGE is introdiced for the backstage deployment object.
b) The user can still override the backstage image using the Backstage CR spec.application.image field.
- Fixes #80 
Deploy the operator and the examples CRs. Check that the backstage app and psql db pods are running successfully.

Enable Operator for restricted network environments

---

.rhdh/bundle/manifests/rhdh-operator.csv.yaml

remove unsupported flag --leader-election-id
I'm seeing a problem starting the operator on my clusterbot 4.14 cluster...
```
flag provided but not defined: -leader-election-id
Usage of /manager:
-health-probe-bind-address string
The address the probe endpoint binds to. (default ":8081")
-kubeconfig string
Paths to a kubeconfig. Only required if out-of-cluster.
-leader-elect
Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.
-metrics-bind-address string
The address the metric endpoint binds to. (default ":8080")
-own-runtime
Making Backstage Controller own runtime objects. If 'true' - all runtime objects created by Controller will be syncing with desired state …
```

remove unsupported flag --leader-election-id

---

controllers/backstage_backend_auth.go
controllers/backstage_controller_test.go

This PR relaxes the condition for creating and injecting default app-config ConfigMap storing the default backend auth key for Backstage.
Previously, it would do so only if `spec.application.appConfig` and `spec.application.extraFiles` and `spec.application.extraEnvs` were not set.
Now, we are only checking that the list of user-defined app-configs in `spec.application.appConfig.configMaps` is non-empty.
&mdash;
Previously, the following CR would not result in a running Backstage container:
```yaml
spec:
application:
appConfig:
mountPath: /opt/app-root/src
extraFiles:
mountPath: /opt/app-root/src
replicas: 1
database:
enableLocalDb: true
```
It should work now with the changes here.

Inject default Backend Auth Key app-config ConfigMap if `spec.application.appConfig.configMaps` is empty

---

bundle/manifests/backstage-operator.clusterserviceversion.yaml
config/manifests/bases/backstage-operator.clusterserviceversion.yaml

Set minKuberVersion to 1.25.0 so that the operator can only be deployed on OpenShift 4.12+.
- Fixes #139 
- [ X] Tests
Check the csv and confirm minKuberVersion is set.

minKubeVersion should be set in the CSV

---

Makefile

Update Makefile to download operator-sdk and opm  and use them for the build
- Fixes #142 
- [X ] Tests
export IMAGE_TAG_BASE=quay.io/<quay org>/backstage-operator
export VERSION=<your version>
make release-build release-push
The build should succeed.

Use locally downloaded operator-sdk and opm for the build

---

.github/workflows/pr-container-build.yaml

At the time [this job](https://github.com/janus-idp/operator/blob/main/.github/workflows/pr-container-build.yaml) runs, the branch might have been deleted already, causing unnecessary failures (+notifications for the PR owner) [1].
Error message seen on a lot of different PRs:
```
A branch or tag with the name '$branch_name' could not be found
```
[1] https://github.com/janus-idp/operator/actions/workflows/pr-container-build.yaml?query=event%3Apull_request_target+is%3Afailure
&mdash;
This job should no longer run when a PR is closed.

Do not try to build the container images when PR is closed

---

controllers/local_db_secret.go

This has been flagged as a potential security issue, which we should avoid doing.
https://github.com/janus-idp/operator/issues/151 will make sure to enforce such checks and detect such issues earlier as we move forward.
cc @kim-tsao 
&mdash;
`kubectl apply -f examples/bs1.yaml` should result in a working Backstage instance.

Do not fallback to a default hard-coded password for PostgreSQL if generation fails

---

api/v1alpha1/backstage_types.go
bundle/manifests/backstage-operator.clusterserviceversion.yaml
controllers/backstage_controller.go
controllers/backstage_controller_test.go
controllers/backstage_deployment.go
controllers/backstage_route.go
controllers/backstage_service.go
controllers/local_db_services.go
controllers/local_db_statefulset.go

When the operator fails to reconcile a CR, it should present an error in the CR's status for troubleshooting. 
When a CR has been successfully, the CR status should indicate that the deployment process is complete.
Simplified CR status conditions to use Deployed only.
Note that the running status support needs more investigation (on the possible impact on performance) and will be postponed to a future CR.
- Fixes #71 (partially)
- [ X] Tests
Deploy example/bs1.yaml and the follow CR status should be displayed indicating sync completion.
```
status:
conditions:
- lastTransitionTime: "2024-01-23T15:06:21Z"
message: ""
reason: DeployOK
status: "True"
type: Deployed
``` 
Now update the CR, set application replicas to -1 and then apply the CR change:
```
apiVersion: janus-idp.io/v1alpha1
kind: …
```

Add error messages to backstage CR status

---

.github/workflows/on-new-issue.yaml

to make sure that every new issue is recorded in Jira as well

chore: label every new issue with jira label

---

.rhdh/bundle/manifests/rhdh-operator.csv.yaml
docs/admin.md

Update the docs related to the security mitigation.
- Fixes #160 
- [ X] Documentation
None

Documentation for security mitigation

---

Makefile
bundle/manifests/backstage-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml

As discussed in [1], it would make sense to use different `VERSION` on `main` and release branches.
[1] https://github.com/janus-idp/operator/pull/200#discussion_r1489312876
&mdash;

Set `VERSION` to `0.1.0` in Makefile for release branch

---

Makefile
bundle/manifests/backstage-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml

As discussed in [1], it would make sense to use different `VERSION` on `main` and release branches.
[1] https://github.com/janus-idp/operator/pull/200#discussion_r1489312876
&mdash;

Set `VERSION` to `0.1.0-dev` in Makefile for `main` branch

---

.github/workflows/next-container-build.yaml

As discussed in [1], this would allow to run `make deploy` out of the box, as the image corresponding to the VERSION in Makefile would be present.
[1] https://github.com/janus-idp/operator/pull/200#discussion_r1489312876
&mdash;
This should fix the issue behind https://github.com/janus-idp/operator/pull/200

Fix tags for images built for main and release branches

---

Makefile
bundle/manifests/backstage-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml

Align `main` to the product version at this time:
```
upstream main ==  0.2.0
upstream 1.1.x branch == 0.1.0
downstream rhdh-1-rhel-9 branch == 1.2.0
downstream rhdh-1.1-rhel-9 branch == 1.1.0
```
&mdash;

Set `VERSION` to `0.2.0` (instead of `0.1.0-dev`) in Makefile for `main` branch

---

.rhdh/bundle/manifests/rhdh-operator.csv.yaml
bundle/manifests/backstage-operator.clusterserviceversion.yaml
config/manifests/bases/backstage-operator.clusterserviceversion.yaml

feat(seamless) chore: add skipranges and replaces logic TODOs, which we can enable when 0.1 and 1.1 are live
alternatively, we could enable this sooner but then to install 1.2 you have to FIRST install 1.1, etc.
N/A
N/A

feat(seamless) chore: add `skipranges` and `replaces` logic TODOs to CSV

---

bundle/manifests/backstage-default-config_v1_configmap.yaml
config/manager/default-config/deployment.yaml
controllers/backstage_controller_test.go

This applies the same fix done in the Helm Chart [1].
As depicted in [2], the init container might fail with insufficient
space error:
```
======= Installing dynamic plugin ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic
==> Grabbing package archive through `npm pack`
Traceback (most recent call last):
File "/opt/app-root/src/install-dynamic-plugins.py", line 304, in <module> main()
File "/opt/app-root/src/install-dynamic-plugins.py", line 230, in main
raise InstallException(f'Error while installing plugin \{ package } with \'npm pack\' : ' + completed.stderr.decode('utf-8')) __main__.InstallException: Error while installing plugin /opt/app-root/src/dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic with 'npm pack' : npm notice …
```

fix: increase default size of the dynamic-plugins-root volume from 1Gi to 2Gi

---

.rhdh/bundle/metadata/annotations.yaml
.rhdh/scripts/prepare-restricted-environment.sh

Signed-off-by: RHDH Build...
chore: [RHIDP-1105](https://issues.redhat.com//browse/RHIDP-1105) switch annotations.yaml back to use fast channels; clean up comments
N/A
https://issues.redhat.com/browse/RHIDP-1105
merge, then merge https://gitlab.cee.redhat.com/rhidp/rhdh/-/merge_requests/8/diffs
build new IIBs in quay
install with either https://github.com/janus-idp/operator/blob/main/.rhdh/scripts/install-rhdh-catalog-source.sh or `build/scripts/installCatalogSourceFromIIB.sh` (from https://gitlab.cee.redhat.com/rhidp/rhdh/)
Reviewers, please comment how you tested the PR when …

chore: RHIDP-1105 switch annotations.yaml back to use fast channels; clean up comments

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pr-bundle-diff-checks.yaml
.github/workflows/pr.yaml
docs/developer.md

This is to ensure bundle manifests are kept updated when submitting a PR. 
This is a follow-up PR to https://github.com/janus-idp/operator/pull/187#issuecomment-1938816003
- ~https://github.com/janus-idp/operator/actions/runs/7878373268?pr=195 is an example of run with outdated bundle manifests~
- ~After applying the resulting patch (attached as a job artifact) or after regenerating the bundle with `make bundle`, the job passes successfully, e.g.: https://github.com/janus-idp/operator/actions/runs/7878650096/job/21497344358?pr=195~
Because the workflow is triggered on `pull_request_target` events, this PR will need to be merged into the base branch to see it in action.

Auto-push bundle manifests changes to PR branch if needed

---

Makefile

Current PR tests are failing due to this error:
`
go: sigs.k8s.io/controller-runtime/tools/setup-envtest@latest (in sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.0.0-20240326031119-8afbb50e0eb2): go.mod:3: invalid go version '1.22.0': must match format 1.23`
as a result of this change https://github.com/kubernetes-sigs/controller-runtime/issues/2720#issuecomment-2016461180
We need to pin to an older commit in order to work around this.
- Fixes #_issue_number_

pin setup-envtest to fix test breakage

---

.github/renovate.json

* Added integration with Github [vulnerability alerts](https://docs.renovatebot.com/configuration-options/#vulnerabilityalerts).  Need to make corresponding repo settings changes to disable Dependabot and Group Security Updates
* Added config for [osvVulnerabilityAlerts](https://docs.renovatebot.com/configuration-options/#osvvulnerabilityalerts).  This is experimental but may be worth trying since it'll raise PRs on vulns found against direct dependencies whereas most, if not all dependabot findings affect transitive dependencies.  
* Removed the `group:linters` and `group:test` presets since these are specific only to js and irrelevant to this repo
- Fixes https://issues.redhat.com/browse/RHIDP-1737

update renovate to include vulnerability alerts

---

api/v1alpha1/backstage_types.go
config/crd/bases/rhdh.redhat.com_backstages.yaml
controllers/backstage_controller_test.go
controllers/backstage_deployment.go

https://issues.redhat.com/browse/RHIDP-1701

overwrite only backstage and init-dynamic-plugins image. fix for https://issues.redhat.com/browse/RHIDP-1701 

---

.github/workflows/nightly.yaml

Otherwise Go 1.21 was available by default in the current runner, and caused the error we saw, like here: https://github.com/janus-idp/operator/actions/runs/8544126445/job/23409466635.
```
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/go-openapi/jsonpointer v0.19.6
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading github.com/emicklei/go-restful/v3 v3.11.0
go: downloading github.com/josharian/intern v1.0.0
go: updates to go.mod needed; to update it:
go mod tidy
mkdir -p /home/runner/work/operator/operator/bin
test -s /home/runner/work/operator/operator/bin/ginkgo || GOBIN=/home/runner/work/operator/operator/bin go install github.com/onsi/ginkgo/v2/ginkgo@v2.17.1
go: downloading github.com/go-task/slim-sprig v0.0.0-20230315185526-52ccab3ef572 …
```

Fix the nightly Workflow by installing the right version of Go

---

.github/workflows/pr-bundle-diff-checks.yaml
.github/workflows/pr-container-build.yaml

Otherwise, this requires manual approval to trigger those workflows
- Add @kim-tsao
- Add @openshift-cherrypick-robot
&mdash;
&mdash;

chore: Update list of GH users not requiring manual approval for `pull_request_target` Workflows

---

controllers/backstage_controller_test.go
pkg/model/deployment.go
pkg/model/deployment_test.go
pkg/model/dynamic-plugins.go
pkg/model/testdata/janus-deployment.yaml
pkg/model/testdata/sidecar-deployment.yaml

fix for https://issues.redhat.com/browse/RHIDP-1701 
https://issues.redhat.com/browse/RHIDP-1701

overwrite only backstage and init-dynamic-plugins image. 

---

.github/workflows/next-container-build.yaml
.github/workflows/nightly.yaml

I realized that some nightly jobs ([example](https://github.com/janus-idp/operator/actions/runs/8607997036/job/23589525220)) could be skipped, but they should have run actually.
To determine if container images needed to be built upon a push, we were looking at the diff between `HEAD` and `HEAD~1`. The problem is that, if there were some additional changes pushed in, say`HEAD~2`, the job would still be skipped even if those changes were relevant for the container image workflow. And this is also why the E2E tests would be skipped.
In this PR, I'm suggesting we always build container images upon any push to the `main` or release branches, and the E2E would always run against the container images built for the most recent commit.
This should help have meaningful E2E tests that always run …

Run E2E tests against the latest/next available operator images

---

examples/bs-existing-secret.yaml
pkg/utils/utils.go

Swapped managed object names from "<CR-name>-backstage" to "backstage-<CR-name>" to make it compatible with 1.1 OOTB
Fixes https://github.com/janus-idp/operator/issues/355
Fixes https://issues.redhat.com/browse/RHIDP-2278

change internal object name to "backstage-<cr-name>"

---

.github/workflows/pr-bundle-diff-checks.yaml
.rhdh/bundle/manifests/rhdh-operator.csv.yaml

There was a difference in the RBAC permissions of the operator between the CSV used for RHDH (https://github.com/janus-idp/operator/blob/main/.rhdh/bundle/manifests/rhdh-operator.csv.yaml) and the upstream one (https://github.com/janus-idp/operator/blob/main/bundle/manifests/backstage-operator.clusterserviceversion.yaml).
This causes issues like the one reported in #360.
- Fixes https://github.com/janus-idp/operator/issues/360
- Fixes https://issues.redhat.com/browse/RHIDP-2325
Diff should only be about the service account name:
```diff
$ diff -U 1 \
<(yq '.spec.install.spec.clusterPermissions' bundle/manifests/backstage-operator.clusterserviceversion.yaml) \
<(yq '.spec.install.spec.clusterPermissions' .rhdh/bundle/manifests/rhdh-operator.csv.yaml)
--- /proc/self/fd/11    2024-05-14 …
```

Fix the RBAC permissions of the Operator in the RHDH CSV

---

examples/rhdh-cr-with-app-configs.yaml
integration_tests/cr-config_test.go
pkg/model/secretfiles_test.go
pkg/utils/utils.go
pkg/utils/utils_test.go

This PR fixes an issue when a ConfigMap or Secret is referenced in the CR and contains a dot (`.`) in its name. The operator would use the ConfigMap/Secret name as is as the volume name in the Deployment Spec, which could be reported as invalid by Kubernetes.
This PR makes sure to sanitize volume names, such that they are RFC 1123-compliant, as depicted in https://kubernetes.io/docs/concepts/overview/working-with-objects/names/.
- Fixes https://issues.redhat.com/browse/RHIDP-2246
See the updated example in [examples/rhdh-cr-with-app-configs.yaml](https://github.com/rm3l/janus-idp-operator/blob/RHIDP-2246--cannot-mount-a-secret-configmap-with-a-.-in-its-name/examples/rhdh-cr-with-app-configs.yaml).
Prior to the changes here, this example would not be reconciled properly. Now it works as …

[RHIDP-2246] Fix reconciliation issue when referenced ConfigMap/Secret has a dot (`.`) in its name

---

config/manifests/bases/backstage-operator.clusterserviceversion.yaml

This fixes the `skipRange` field in the base CSV on the `main` branch.
After rebasing https://github.com/janus-idp/operator/pull/369 onto `main`, I noticed a change to the generated bundle, which should not have occurred there.
This is a follow-up to https://github.com/janus-idp/operator/pull/375

Fix version number in `skipRange` and `name` fields in base CSV

---

.github/workflows/nightly.yaml

Now that the `1.2.x` branch has been created, it makes sense to run the nightly jobs against it.
Also, because of our image expiration policy, nightly jobs might fail if the operator image has expired (e.g., because the corresponding branch had not been updated for a long time). Example [here](https://github.com/janus-idp/operator/actions/runs/9342020815/job/25709492555).
In such case, it does not make sense for the nightly job to fail. Instead, this PR makes it display a simple warning message in the Workflow summary.
&mdash;
See an example of a Workflow Run here: https://github.com/rm3l/janus-idp-operator/actions/runs/9365256636

ci: Run Nightly job against the `1.2.x` branch as well and skip job if operator image has expired

---

.rhdh/bundle/manifests/rhdh-operator.csv.yaml
Makefile
bundle/manifests/backstage-operator.clusterserviceversion.yaml

feat: tagRelease.sh bump versions in 1.2.x for 1.2 release

---

.github/workflows/nightly.yaml

This fixes the nightly jobs that have been failing for the past few days. See https://github.com/janus-idp/operator/actions/runs/9705023377/job/26786334075
Nightly jobs should pass.

chore(CI): Skip the Operator Upgrade tests if the image for the current branch has expired

---

.rhdh/docs/installing-ci-builds.adoc

This is no longer needed since the [rhdh organization](https://quay.io/organization/rhdh) is public on Quay.
&mdash;
Just run `.rhdh/scripts/install-rhdh-catalog-source.sh --latest --install-operator rhdh`, and the operator should be installed without any need for adding your Quay token as a global pull secret in OCP.

docs: Remove the need for adding a Quay token as a global pull secret in the RHDH CI install procedure

---

examples/rhdh-cr.yaml

1.0 is no longer supported and does not make sense to be used as example (and in the E2E tests).
'latest' here can be seen as quite stable as it is the latest Release Candidate or GA image.
This also removes the unnecessary image pull secret from the RHDH CR example, because the rhdh organization is public on Quay.
&mdash;
`make test-e2e`  against a real cluster should continue to pass.

chore(examples): Use `latest` RHDH image tag and remove useless pull secret in RHDH CR example

---

.rhdh/docs/openshift.adoc
bundle/manifests/backstage-default-config_v1_configmap.yaml
bundle/manifests/backstage-operator.clusterserviceversion.yaml
config/manager/default-config/app-config.yaml
examples/rhdh-cr-with-app-configs.yaml
examples/rhdh-cr.yaml
pkg/model/testdata/raw-app-config.yaml
tests/e2e/testdata/backstage-operator-0.1.3.yaml

Fixed default configuration to remove deprecation warning about backend.auth.keys by replacing it with https://github.com/backstage/backstage/blob/master/beps/0007-auth-external-services/README.md#the-legacy-access-type 
Fixes: https://issues.redhat.com/browse/RHIDP-2716

Remove deprecation warning about backend.auth.keys

---

.github/workflows/nightly.yaml
bundle/manifests/backstage-default-config_v1_configmap.yaml
bundle/manifests/backstage-operator.clusterserviceversion.yaml
config/manager/default-config/deployment.yaml
config/manager/manager.yaml
examples/bs1.yaml
examples/rhdh-cr-with-app-configs.yaml
tests/e2e/e2e_suite_test.go
tests/e2e/e2e_test.go
tests/e2e/e2e_upgrade_test.go
tests/e2e/testdata/backstage-operator-0.1.3.yaml
tests/helper/helper_backstage.go

This PR fixes the failing nightly job by:
- switching the default operand image from `quay.io/janus-idp/backstage-showcase:latest` to ~`quay.io/rhdh/rhdh-hub-rhel9:latest`~ `quay.io/janus-idp/backstage-showcase:next`.
We'll need to monitor our tests to see how they behave against this `next` tag (built from the `main` branch of the Showcase repo). If they are too unstable, we might need to switch back to using a stable (and updated) downstream RHDH image.
- making sure to handle the required (RHDH 1.2+) authentication to the `/api/dynamic-plugins-info/loaded-plugins` endpoint (used in the tests to ensure a fully-working CR example)
- Fixes https://issues.redhat.com/browse/RHIDP-3157
See https://github.com/rm3l/janus-idp-operator/actions/runs/9960353647/job/27520205261 as an example of a …

chore: Switch the default operand image tag from `latest` to `next` and fix CI nightly job [RHIDP-3157]

---

examples/postgres-secret.yaml
examples/showcase-config.yaml

A user relied on this example to override their raw config, but the operator silently ignored it.
- Fixes https://issues.redhat.com/browse/RHDHBUGS-44
```
kubectl apply -f examples/postgres-secret.yaml
kubectl apply -f examples/showcase-config.yaml
kubectl apply -f examples/showcase-cr.yaml
```
Should work and should apply the custom config.

fix(examples): Fix key in ConfigMap used in example CR with `rawRuntimeConfig` [RHDHBUGS-44]

---

api/v1alpha1/backstage_types.go
api/v1alpha2/backstage_types.go
bundle/manifests/backstage-operator.clusterserviceversion.yaml
bundle/manifests/rhdh.redhat.com_backstages.yaml
config/crd/bases/rhdh.redhat.com_backstages.yaml

This is a follow-up to https://issues.redhat.com/browse/RHDHBUGS-45
Right now, using the Operator, a user can reference an external certificate as a Secret in their CR, like so:
```yaml
spec: 
application: 
route: 
enabled: true
host: my-rhdh.apps.example.com
tls: 
externalCertificateSecretName: my-rhdh-tls-cert
```
However, as depicted in https://docs.openshift.com/container-platform/4.16/networking/routes/secured-routes.html#nw-ingress-route-secret-load-external-cert_secured-routes, **Securing route with external certificates in TLS secrets is a Technology Preview feature only**. As such, it requires enabling the `RouteExternalCertificate` Feature Gate in OpenShift.
This updates the doc about the `spec.application.route.tls.externalCertificateSecretName` CRD field accordingly.
Note that …

docs: add note in CRD that using Routes with external certificates in TLS Secrets is Technical Preview in OCP [RHDHBUGS-45]
