janus-idp/operator

- .github/workflows/pr.yaml
- Makefile
- bundle/manifests/backstage-operator.clusterserviceversion.yaml
chore: add note about multiple-arch build option with buildx; remove unsupported arches from CSV and Makefile
related to https://issues.redhat.com/browse/RHIDP-488
> chore: add note about multiple-arch build option with buildx; remove unsupported arches from CSV and Makefile

- docker/Dockerfile
- docker/brew.Dockerfile
chore: bump to ubi 9.3 and go-toolset 1.20
N/A
N/A
> chore: bump to ubi 9.3 and go-toolset 1.20

- .rhdh/bundle/manifests/rhdh-operator.csv.yaml
chore: fix: s/RELATED_IMAGE_hub/RELATED_IMAGE_backstage
N/A
N/A
> chore: fix: s/RELATED_IMAGE_hub/RELATED_IMAGE_backstage

- .github/workflows/pr-docker-build.yaml
Signed-off-by:...
trigger on pushes to main
N/A
N/A
> trigger on pushes to main

- .github/workflows/pr-docker-build.yaml
- OWNERS
switch to use pull_request_target and authorize step (#73); add nickboldt as owner
N/A
N/A
> switch to use pull_request_target and authorize step; add nickboldt as owner

- Makefile
Signed-off-by: RHDH...
chore: typo/formatting
N/A
N/A
> chore: typo/formatting

- .rhdh/bundle/manifests/rhdh-operator.csv.yaml
- .rhdh/docker/Dockerfile
- docker/Dockerfile
feat: enable FIPS compliance by switching to ubi9 minimal and installing openssl; add Infrastructure Feature Test annotations ([RHIDP-294](https://issues.redhat.com//browse/RHIDP-294))
N/A
N/A
> feat: enable FIPS compliance by switching to ubi9 minimal and installing openssl; add Infrastructure Feature Test annotations (RHIDP-294)

- .rhdh/bundle/manifests/rhdh-operator.csv.yaml
chore: [RHIDP-294](https://issues.redhat.com//browse/RHIDP-294) switch to booleanesque strings, not actual booleans, because CVP implementation is dumb
N/A
N/A
> chore: RHIDP-294 switch to booleanesque strings, not actual booleans, because CVP implementation is dumb

- OWNERS
> Update OWNERS - change reference to pr-container-build action

- .github/workflows/pr.yaml
- .gitignore
- Makefile
- docs/developer.md
1.  Send index.Docker to ./dockerfile instead of root and .gitignore it
2. Remove Sqlite database after index image build
3. Rename tag operator-build/-push to image-build/-push as (not ideal but) less confusing (manager image != operator and $ (MAKE) operator-push IMG=$(BUNDLE_IMG) does not look logical) and fix doc accordingly
4. Add deploy-openshift tag and document in developer.md
> Clean opm output and fix developer.md 

- .github/workflows/pr.yaml
- .gitignore
- Makefile
- controllers/backstage_controller.go
- controllers/local_db_secret.go
- Adds the scanner to our github workflow so it can run as part of our PR checks
- Handle initial findings
- Fixes #_issue_number_
-
https://github.com/janus-idp/operator/issues/151
> Enable gosec scanning

- .github/workflows/next-container-build.yaml
- .github/workflows/pr-container-build.yaml
Fixes some invalid patterns preventing those Workflows from running.
See the latest failures reported here: https://github.com/janus-idp/operator/actions?query=is%3Afailure
&mdash;
> Fix invalid branch pattern in GitHub Workflows

- controllers/backstage_controller.go
- controllers/backstage_controller_test.go
- controllers/suite_test.go
Remove clientset variable from the previous PR. It is no longer needed.
- Fixes #153 
No functional changes.
> Code cleanup: remove un-used clientset

- config/crd/bases/rhdh.redhat.com_backstages.yaml
[The recent PR](https://github.com/janus-idp/operator/pull/214) to fix a typo required a manifest update
- Fixes #_issue_number_
> regen manifest

- .github/renovate.json
chore: enable digest pinning and major updates in dockerfiles; attempt to split go and docker into separate updates (different branch prefixes)
N/A
N/A
> chore: enable digest pinning and major updates in dockerfiles; attempt to split go and docker into separate updates (different branch prefixes)

- .github/renovate.json
> Update renovate.json - remove non-working code

- .github/renovate.json
chore: security: automerge patch updates to dockerfile base image refs
don't enable merging major or minor - unexpected changes happen with go version bumps from 1.20 -> 1.21, but we want all 1.20.* updates
N/A
N/A
> chore: security: automerge patch version updates to dockerfiles in main and 1.*.x

- .github/renovate.json
chore: switch from matchCategories to matchDatasources; explicitly disable pin/pinDigest/digest PRs
N/A
N/A
> chore: switch from matchCategories to matchDatasources; explicitly disable pin/pinDigest/digest PRs

- bundle/manifests/backstage-default-config_v1_configmap.yaml
- bundle/manifests/backstage-operator.clusterserviceversion.yaml
- config/manager/default-config/deployment.yaml
add resources.requests to default config
https://issues.redhat.com/browse/RHIDP-2159
> add resources.requests to default config

- .rhdh/scripts/install-rhdh-catalog-source.sh
chore: [RHIDP-1998](https://issues.redhat.com//browse/RHIDP-1998) use skopeo to verify if the image from which we plan to create a catalog source exists before attempting to use it;
note: this introduces a dependency on skopeo, which could impact automated tests that use this script
See also https://github.com/janus-idp/operator/blob/main/.rhdh/docs/installing-ci-builds.adoc#installing-ci-builds-of-red-hat-developer-hub
N/A
N/A
> chore: RHIDP-1998 use skopeo to verify if the image from which we plan to create a catalog source exists before attempting to use it

- .github/workflows/pr-bundle-diff-checks.yaml
- .github/workflows/pr-container-build.yaml
- .rhdh/bundle/manifests/rhdh-operator.csv.yaml
- OWNERS
- bundle/manifests/backstage-operator.clusterserviceversion.yaml
- config/manifests/bases/backstage-operator.clusterserviceversion.yaml
This simply cleans up the list of owners and maintainers, to reduce the number of review requests automatically sent out to people no longer actively working on the project.
&mdash;
&mdash;
> chore: Update list of owners and maintainers

- .rhdh/bundle/manifests/rhdh-operator.csv.yaml
- bundle/manifests/backstage-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- pkg/utils/utils_test.go
Fix for https://issues.redhat.com/browse/RHIDP-2036 v 1.2
> increase controller memory

- docs/external-db.md
Added external DB configuration documentation
https://issues.redhat.com/browse/RHIDP-2016
> external db documentation

- .rhdh/bundle/manifests/rhdh-operator.csv.yaml
- Fixed telemetry URL
- Added "Telemetry Data Collection" heading before the warning
- Fixes https://issues.redhat.com/browse/RHIDP-1907
> fixed telemetry url

- .rhdh/bundle/manifests/rhdh-operator.csv.yaml
- Makefile
- bundle/manifests/backstage-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/backstage-operator.clusterserviceversion.yaml
> feat: tagRelease.sh bump versions in 1.2.x for 1.2.2 release

- controllers/backstage_controller.go
Currently the reconciler watches for Secret and ConfigMap related events and the `controller-runtime` cashes all the respective resources from the cluster in memory. That can be quite memory consuming in clusters with lots of such resources.
When the operator is deployed to the cluster with ~60k secrets and ~6.5k configmaps in it, it fills up all the memory and crashes with out-of-memory error.
Following the guidelines in the [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/builder/controller.go#L151) comments in code, this PR switches from watching with `Secret` and `ConfigMap` full objects to the use of `PartialObjectMetadata` representing to the `Secret` and `ConfigMap` resources.
With this patch the operator memory kept under the 800M max and …
> fix(RHIDP-2920): switch Secret and ConfigMap watches to WatchMetadata to reduce memory consumption

- bundle/manifests/backstage-default-config_v1_configmap.yaml
- bundle/manifests/backstage-operator.clusterserviceversion.yaml
- config/manager/default-config/deployment.yaml
- integration_tests/rhdh-config_test.go
Update the security context to more closely align with the Helm Chart settings.
- Fixes #_issue_number_
> chore: Update security context to be in line with Helm Chart

- .rhdh/bundle/manifests/rhdh-operator.csv.yaml
Add note to operator install description about option to use external db
JIRA issue: https://issues.redhat.com/browse/RHIDP-1148?filter=-1
> RHIDP-1148-add-external-db-note
